### ISSUE TITLE
Extend instructions

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arc2repo#2]
Can you extend the instructions to indicate the expected outcome? 
The converter (docker image) seems to run, but I'm not sure what's supposed to happen.

**Comment by Brilator** [comment]
What are the files `json_table_new.csv` and `STUDY.xml` good for?

**Comment by xiaoranzhou** [comment]
STUDY.XML is one file that can be submitted to the ENA. https://ena-docs.readthedocs.io/en/latest/submit/general-guide/interactive.html
